name: Deploy Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir dist
          echo "<h1>Hello Pages</h1>" > dist/index.html
      - name: Upload Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
      - name: Deploy Pages
        uses: actions/deploy-pages@v1